export global T {
    out property <color> bg:      #12111a;
    out property <color> panel:   #1c1b26;
    out property <color> raised:  #26243488;
    out property <color> border:  #33304a;
    out property <color> acc:     #a78bfa;
    out property <color> acc-bg:  #2d2457;
    out property <color> acc-fg:  #f0ebff;
    out property <color> fg:      #e2e0eb;
    out property <color> fg-dim:  #7c7a8e;
    out property <color> err:     #f87171;
    out property <color> ok:      #4ade80;
}
